<div align="center">
  <img
    src="./profile/trophy.svg"
    height="150"
    alt="GitHub Trophies"
  />
</div>

<br>

<div align="center">
  <picture>
    <source
      media="(prefers-color-scheme: dark)"
      srcset="https://raw.githubusercontent.com/0xAbhi13/0xAbhi13/output/pacman-contribution-graph-dark.svg"
    />
    <source
      media="(prefers-color-scheme: light)"
      srcset="https://raw.githubusercontent.com/0xAbhi13/0xAbhi13/output/pacman-contribution-graph.svg"
    />
    <img
      src="https://raw.githubusercontent.com/0xAbhi13/0xAbhi13/output/pacman-contribution-graph.svg"
      alt="Pac-Man Contribution Graph"
    />
  </picture>
</div>
